In [1]:
import sys
sys.path.append("../src/")

In [2]:
# Local imports
from data.make_dataset import *
from models.regressor import *
from models.predict import *
from visualization.visualize import *

In [3]:
%%time  

# This function reads train data(features & target) and merges into single dataframe
df = make_train_dataset()

Shape of Feature dataset: (260601, 39)
Shape of Target dataset: (260601, 2)
CPU times: user 681 ms, sys: 214 ms, total: 895 ms
Wall time: 902 ms

In [4]:
%%time

# Class Classifer invokes setup() method from pycaret.regression
clf=Regressor(df)

CPU times: user 41.2 s, sys: 5.44 s, total: 46.7 s
Wall time: 44.4 s

In [5]:
%%time

# This function creates baseline model with ‘lightgbm’ - Light Gradient Boosting Machine as estimator
baseline=clf.create_baseline_model()

CPU times: user 1min 2s, sys: 1.75 s, total: 1min 4s
Wall time: 8.66 s

In [6]:
%%time

# This function analyzes the performance of a trained model with 
# different plots
plot_report(baseline)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

CPU times: user 984 ms, sys: 87.8 ms, total: 1.07 s
Wall time: 175 ms

In [7]:
%%time

# This function creates tuned model with hyperparameters 
# (learning_rate, n_estimators, num_leaves, reg_alpha, reg_lambda)
tuned_model=clf.create_tuned_model()

CPU times: user 2min 25s, sys: 3.1 s, total: 2min 29s
Wall time: 19.9 s

In [8]:
# This function analyzes the performance of a tuned model with 
# plot/estimator as ‘class_report’ - regression Report
plot_report(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [9]:
# This function finalizes trianed model with the splitted train and test data.
tuned_model=clf.finalize(tuned_model)

In [10]:
# This function reads test data
test_dataset = make_test_dataset()

Shape of Test dataset: (86868, 39)

In [11]:
%%time

# Predicts Target & Score (probability of predicted class) using a trained model,
# then save the prediction in csv file.
predict_and_store_result(tuned_model, test_dataset)

CPU times: user 8.19 s, sys: 794 ms, total: 8.98 s
Wall time: 5.6 s